import type { Metadata } from "next";
import { Providers } from "./providers";
import Script from "next/script";

import { Geist } from "next/font/google";
import "./globals.css";
import Main from "../layout/Main";
import Navbar from "../layout/Navbar";
import Footer from '../layout/Footer'
import ScrollToTopButton from "../component/ScrollToTopButton";
import ModalManager from "../component/ModalManager";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body  className={`${geistSans.variable} antialiased`}>
        <Providers>
          <ScrollToTopButton />
          <Navbar />
          <Main>{children}</Main>
          <Footer />
          <ModalManager />
        </Providers>
        
         <Script
        src="https://accounts.google.com/gsi/client"
        strategy="beforeInteractive"
      />
      </body>
    </html>
  )
}
